# -*- coding: utf-8 -*-
"""AI Brain Tumor Detection & Segmentation System using Deep Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hvPVAEx2Utt8KtPXvQ4Q-e1nxYMjSI5Q
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("dschettler8845/brats-2021-task1")

print("Path to dataset files:", path)

!pip install nibabel matplotlib

import os

base_path = "/kaggle/input/brats-2021-task1"

for root, dirs, files in os.walk(base_path):
    if len(files) > 0:
        print(root)
        print(files[:3])
        print("-----")

import os

base_path = "/kaggle/input/brats-2021-task1"

for root, dirs, files in os.walk(base_path):
    if len(files) > 0:
        print("\n📁", root)
        for f in files[:5]:
            print("   ", f)

import os

base_path = "/kaggle/input/brats-2021-task1"

flair_path = None
seg_path = None

for root, dirs, files in os.walk(base_path):
    for f in files:
        if "flair" in f:
            flair_path = os.path.join(root, f)
        if "seg" in f:
            seg_path = os.path.join(root, f)

print("FLAIR:", flair_path)
print("SEG:", seg_path)

import os

base_path = "/kaggle/input/brats-2021-task1"

for root, dirs, files in os.walk(base_path):
    for f in files[:3]:
        print(root, " → ", f)

import os

base_path = "/kaggle/input/brats-2021-task1"

flair_path = None
seg_path = None

for root, dirs, files in os.walk(base_path):
    for f in files:
        if "flair" in f.lower():
            flair_path = os.path.join(root, f)

        if "seg" in f.lower():
            seg_path = os.path.join(root, f)

        if flair_path and seg_path:
            break

print("FLAIR:", flair_path)
print("SEG:", seg_path)

if flair_path is None or seg_path is None:
    print("❌ لم يتم العثور على الملفات - تأكد من الداتاست")
else:
    print("✅ تم العثور على الملفات")

import os

base_path = "/kaggle/input/brats-2021-task1"

for item in os.listdir(base_path):
    print(item)

import tarfile
import os

file_path = "/kaggle/input/brats-2021-task1/BraTS2021_Training_Data.tar"
extract_path = "/kaggle/working/brats"

os.makedirs(extract_path, exist_ok=True)

with tarfile.open(file_path) as tar:
    tar.extractall(path=extract_path)

print("✅ تم فك الضغط")

import os

for root, dirs, files in os.walk("/kaggle/working/brats"):
    if len(files) > 0:
        print(root)
        print(files[:3])
        print("-----")

import os

base_path = "/kaggle/working/brats"

for root, dirs, files in os.walk(base_path):
    for f in files[:3]:
        print(root, "→", f)

import os

base_path = "/kaggle/working/brats"

flair_path = None
seg_path = None

for root, dirs, files in os.walk(base_path):
    for f in files:
        if "flair" in f.lower():
            flair_path = os.path.join(root, f)

        if "seg" in f.lower():
            seg_path = os.path.join(root, f)

        if flair_path and seg_path:
            break

print("FLAIR:", flair_path)
print("SEG:", seg_path)

if flair_path is None or seg_path is None:
    print("❌ الملفات غير موجودة")
else:
    print("✅ جاهز للاستخدام")

import nibabel as nib
import matplotlib.pyplot as plt

img = nib.load(flair_path).get_fdata()
mask = nib.load(seg_path).get_fdata()

slice_idx = img.shape[2] // 2

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(img[:,:,slice_idx], cmap='gray')
plt.title("MRI")

plt.subplot(1,2,2)
plt.imshow(img[:,:,slice_idx], cmap='gray')
plt.imshow(mask[:,:,slice_idx], alpha=0.5, cmap='Reds')
plt.title("Tumor")

import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt

img = nib.load(flair_path).get_fdata()
mask = nib.load(seg_path).get_fdata()

slice_idx = img.shape[2] // 2

img_slice = img[:, :, slice_idx]
mask_slice = mask[:, :, slice_idx]

plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.imshow(img_slice, cmap='gray')
plt.title("MRI Brain")
plt.axis('off')

plt.subplot(1,2,2)
plt.imshow(img_slice, cmap='gray')
plt.imshow(mask_slice, alpha=0.5, cmap='Reds')
plt.title("Tumor Location")
plt.axis('off')

plt.show()

tumor_pixels = np.sum(mask_slice > 0)
total_pixels = mask_slice.size

tumor_ratio = (tumor_pixels / total_pixels) * 100

print("📏 نسبة الورم:", round(tumor_ratio, 2), "%")

unique = np.unique(mask_slice)
print("أنواع القيم داخل الورم:", unique)

print("Necrotic:", np.sum(mask_slice == 1))
print("Edema:", np.sum(mask_slice == 2))
print("Enhancing:", np.sum(mask_slice == 4))

colored_mask = np.zeros((*mask_slice.shape, 3))

colored_mask[mask_slice == 1] = [255, 0, 0]   # أحمر
colored_mask[mask_slice == 2] = [0, 255, 0]   # أخضر
colored_mask[mask_slice == 4] = [0, 0, 255]   # أزرق

plt.imshow(img_slice, cmap='gray')
plt.imshow(colored_mask, alpha=0.5)
plt.title("Tumor Types Visualization")
plt.axis('off')